import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import moment from "moment";
import "moment/locale/es"; // without this line it didn't work
import Logo from "../public/images/logo-carrefour.png";

export default function Home() {
  /*   $(document).ready(function () {
    var weeknumber = moment("11-26-2016", "MMDDYYYY").isoWeek();
    alert(weeknumber);
  }); */
  moment.locale("fr");
  let now = moment().format();
  var weekNumber = moment(now, "DD-MM-YYYY").isoWeek();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Carrefour Saint-pol-sur-mer</h1>
        <Image src={Logo} />
        <h3>Nous sommes la semaine {`${weekNumber}`}</h3>
        <div className={styles.grid}>
          <Link href="/epicerie/epicerie" className={styles.card}>
            <a>
              <h2>Epicerie &rarr;</h2>
            </a>
          </Link>

          <Link href="/liquide" className={styles.card}>
            <a>
              <h2>Liquide &rarr;</h2>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>dev by Lionel Ignaes</footer>
    </div>
  );
}
