import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import moment from "moment";
import "moment/locale/fr";
import Logo from "../public/images/logo-carrefour.png";
import getFrenchWeekNumber from "../utils/weekNumber.js";

export default function Home() {
  moment.locale("fr");

  let dayName = moment().format("LL");
  let weekNumber = getFrenchWeekNumber();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Carrefour Saint-pol-sur-mer</h1>

        <Image src={Logo} />
        <br />
        <h3>Nous sommes le {dayName}</h3>
        <h3>Semaine : {weekNumber}</h3>

        <Link href="/epicerie/">
          <a className={styles.box}>
            <h2>Epicerie &rarr;</h2>
          </a>
        </Link>

        <Link href="/liquide">
          <a className={styles.box}>
            <h2>Liquide &rarr;</h2>
          </a>
        </Link>
      </main>

      <footer className={styles.footer}>dev by Lionel Ignaes</footer>
    </div>
  );
}
